export const iconFrames = [
  { name: "ブロンズフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_branze.png" },
  { name: "シルバーフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_silver.png" },
  { name: "ゴールドフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_gold.png" },
  { name: "プラチナフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_platinum.png" },
  { name: "レインボーフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_rainbow.png" },
  { name: "ピンクフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_pink.png" },
  { name: "ネイビーフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_navy.png" },
  { name: "ダークグレーフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_darkgray.png" },
  { name: "グリーンフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_green.png" },
  { name: "レッドフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_red.png" },
  { name: "ゴールドレッドフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_goldred.png" },
  { name: "ブルーシアンフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_bluecyan.png" },
  { name: "パープルピンクフレーム", imgUrl: "https://drive-quest-s3.s3.ap-northeast-1.amazonaws.com/icon_frame/iconframe_purplepink.png" },
]; 